# Generated by Django 3.2.6 on 2021-08-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=70)),
                ('day', models.CharField(max_length=70)),
                ('time', models.CharField(max_length=50)),
            ],
        ),
    ]
