# Generated by Django 2.2.7 on 2021-08-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_first_name', models.CharField(max_length=50, null='False')),
                ('emp_last_name', models.CharField(max_length=50, null='False')),
                ('emp_Email', models.EmailField(default='', max_length=50)),
                ('emp_Skill', models.CharField(default='', max_length=50)),
                ('emp_from_exp', models.CharField(default='', max_length=50)),
                ('emp_to_exp', models.CharField(default='', max_length=50)),
                ('emp_date', models.CharField(default='', max_length=50)),
                ('emp_start_time', models.CharField(max_length=50)),
                ('emp_end_time', models.CharField(max_length=50)),
            ],
        ),
    ]
