# Generated by Django 3.2.6 on 2021-08-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_first_name', models.CharField(max_length=50)),
                ('emp_last_name', models.CharField(max_length=50)),
                ('emp_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('emp_Email', models.EmailField(max_length=50)),
                ('emp_Phone', models.CharField(max_length=50)),
                ('emp_Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50)),
                ('emp_Experience', models.CharField(max_length=50)),
                ('emp_Skill', models.CharField(max_length=50)),
                ('time_Week', models.CharField(choices=[('W1', 'Week1'), ('W2', 'Week2'), ('W3', 'Week3'), ('W4', 'Week4')], max_length=50)),
                ('time_Day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=50)),
                ('time_Slot', models.CharField(max_length=50)),
            ],
        ),
    ]
