# Generated by Django 3.2.6 on 2021-08-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='time',
            field=models.FloatField(),
        ),
    ]
