# Generated by Django 3.2.6 on 2021-08-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0003_auto_20210826_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('password2', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
