# Generated by Django 3.2.6 on 2021-08-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0004_auto_20210826_1746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HR',
            new_name='Human_Resources',
        ),
    ]
