# Generated by Django 3.2.6 on 2021-08-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0006_auto_20210826_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=50)),
                ('from1', models.FloatField(max_length=20)),
                ('to', models.FloatField(max_length=20)),
            ],
        ),
    ]
