# Generated by Django 2.2.7 on 2021-08-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0006_auto_20210827_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emps',
            name='emp_end_time',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emps',
            name='emp_from_exp',
            field=models.FloatField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='emps',
            name='emp_start_time',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emps',
            name='emp_to_exp',
            field=models.FloatField(default='', max_length=50),
        ),
    ]
