# Generated by Django 2.2.7 on 2021-08-27 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0007_auto_20210827_0842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emps',
            new_name='Emp',
        ),
    ]
