# Generated by Django 3.2.6 on 2021-08-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0007_slot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emp',
        ),
    ]
