# Generated by Django 3.2.6 on 2021-08-30 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0008_delete_emp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewer',
            name='lname',
        ),
    ]
