# Generated by Django 3.2.6 on 2021-08-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0009_remove_interviewer_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
